# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170302_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('about', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
    ]
